server_info:
  host: '127.0.0.1'
  port: 8801
  group: 'dev'
  name: "user-srv"
jwt:
  key: 'pengze'

consul_info:
  host: '192.168.122.114'
  port: 8500
  name: 'pengze-shop-web'

redis_info:
  host: '127.0.0.1'
  port: 6379
  expire: 24
  db: 0
